In [12]:
import sqlite3
import pandas as pd

In [ ]:
# Connect to the database
conn = sqlite3.connect('c:\\baykar_project\\data\\logs\\chat_logs.db')

# View all tables
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("Tables in database:", tables['name'].tolist())

Tables in database: ['api_logs', 'sqlite_sequence', 'chat_sessions', 'chat_messages']

In [14]:
sqlite_sequence = pd.read_sql_query("SELECT * FROM sqlite_sequence", conn)
print("\nsqlite_sequence:")
sqlite_sequence

sqlite_sequence:

            name   seq
0       api_logs  1257
1  chat_sessions     2
2  chat_messages     6

In [15]:
# View API logs
api_logs = pd.read_sql_query("SELECT * FROM api_logs", conn)
print("\nAPI Logs:")
api_logs

API Logs:

,id,timestamp,question,answer,retrieved_sources,retrieval_time,generation_time,total_time
0,1,2025-09-15T19:49:26.524737,What are the definitions of White Coat Phenome...,"Based on the provided knowledge base, the defi...","[""nihms837917.pdf"", ""11906_2024_Article_1309.p...",0.312598,7.838029,8.168169
1,2,2025-09-15T19:49:28.967680,What is the 'alerting reaction' in the context...,"The ""alerting reaction"" is a phenomenon where ...","[""nihms837917.pdf"", ""11906_2024_Article_1309.p...",0.010211,2.393854,2.411967
2,3,2025-09-15T19:49:34.890562,What factors are associated with a higher like...,"Based on the provided knowledge base, there is...","[""IJMR-161-1-99.pdf"", ""nihms-1698921.pdf"", ""gh...",0.010291,5.878135,5.896555
3,4,2025-09-15T19:49:43.794926,What was the prevalence of Left Ventricular Di...,"Based on the provided knowledge base, I found ...","[""nihms-1698921.pdf"", ""nihms-1766793.pdf"", ""gh...",0.010329,8.878684,8.897488
4,5,2025-09-15T19:49:44.636370,"According to the study on LVDD, what is the pr...",I do not have sufficient information to answer...,"[""nihms-1766793.pdf"", ""jeae097.pdf"", ""gh-19-1-...",0.011756,0.816934,0.835464
...,...,...,...,...,...,...,...,...
1252,1253,2025-09-16T14:54:44.961673,How did ACE inhibitors and ARBs compare in the...,I do not have sufficient information to answer...,"[""13000_2023_Article_1393.pdf"", ""vhrm-18-507.p...",0.010507,1.239391,1.257993
1253,1254,2025-09-16T14:54:46.234172,In the subgroup of hypertensive patients with ...,I do not have sufficient information to answer...,"[""vhrm-18-507.pdf"", ""13000_2023_Article_1393.p...",0.010800,1.230587,1.248530
1254,1255,2025-09-16T14:54:47.419206,What is HOMA-IR?,I do not have sufficient information to answer...,"[""jhype-40-033.pdf"", ""JCH-27-e14942.pdf"", ""JAH...",0.010263,1.154598,1.171966
1255,1256,2025-09-16T14:54:48.670714,Was hypertension associated with a higher risk...,I do not have sufficient information to answer...,"[""41440_2023_Article_1484.pdf"", ""nihms-1698921...",0.011938,1.190660,1.210000
1256,1257,2025-09-16T14:54:49.954360,"In treated hypertensive individuals, what was ...",I do not have sufficient information to answer...,"[""nihms-1698921.pdf"", ""hpad090.pdf"", ""nihms837...",0.010222,1.239114,1.256999

In [16]:
# View API logs
chats = pd.read_sql_query("SELECT * FROM chat_sessions", conn)
print("\nChats:")
chats

Chats:

   id       session_id                  created_at
0   1  20250916_123944  2025-09-16T12:39:44.497187
1   2  20250916_143945  2025-09-16T14:39:45.255692

In [17]:
# View API logs
chat_messages = pd.read_sql_query("SELECT * FROM chat_messages", conn)
print("\nChat Messages:")
chat_messages

Chat Messages:

,id,session_id,timestamp,role,content
0,1,20250916_123944,2025-09-16T12:39:44.500188,user,What was the prevalence of Left Ventricular Di...
1,2,20250916_123944,2025-09-16T12:39:44.503187,assistant,"Based on the provided knowledge base, there is..."
2,3,20250916_143945,2025-09-16T14:39:45.260693,user,What is the definition of the White Coat Pheno...
3,4,20250916_143945,2025-09-16T14:39:45.264545,assistant,I do not have sufficient information to answer...
4,5,20250916_143945,2025-09-16T14:40:06.033337,user,Is White Coat Uncontrolled Hypertension (WUCH)...
5,6,20250916_143945,2025-09-16T14:40:06.036337,assistant,WUCH is not explicitly mentioned in the provid...

In [18]:
conn.close()